steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/${_REPO}:$TAG_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','us.gcr.io/$PROJECT_ID/${_REPO}:$TAG_NAME']       
substitutions:
  _REPO: gcp-docker-test 