steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','us.gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME']  
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - set
    - image
    - deployment
    - $PROJECT_ID
    - us.gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME
    - env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
images:
  - 'us.gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME'
tags: ['$TAG_NAME']          