steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','us.gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME']        